apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes-manifests
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  type: NodePort
  ports:
    - name: "50009"
      port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
